---
- name: Provision trilium data volume
  hosts: all
  become: true
  vars:
    volume_serial:
    mount_path: /mnt/app_data
    filesystem: ext4
  tasks:
    - name: Get device name of data volume
      shell: lsblk -o +SERIAL | grep {{ volume_serial }} | awk '{print $1}'
      register: device_name
    - name: Format the data volume
      filesystem:
        dev: "/dev/{{ device_name.stdout }}"
        fstype: "{{ filesystem }}"
    - name: Mount the data volume
      mount:
        name: "{{ mount_path }}"
        src: "/dev/{{ device_name.stdout }}"
        fstype: "{{ filesystem }}"
        state: mounted
